---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: rubythalib/integratedapi:latest
        ports:
        - containerPort: 8000
        env:
        - name: MONGO_HOST
          value: "mongo"
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30005
