# pv-mongodb-statefulset.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongodb-0
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mongodb-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongodb-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mongodb-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongodb-2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mongodb-2